=== molekulardynamik/projekt/config.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:complexType name="statistics_t">
		<xs:attribute name="filename" type="xs:string" default="profile"/>
		<xs:attribute name="iterations" type="xs:int" default="100000"/>
	</xs:complexType>
	<xs:complexType name="output_t">
		<xs:sequence>
			<xs:element name="dir" type="xs:string"/>
			<xs:element name="filename" type="xs:string"/>
			<xs:element name="iterations" type="xs:int"/>
			<xs:element name="velocityProfile" type="statistics_t" minOccurs="0"/>
			<xs:element name="diffusion" type="statistics_t" minOccurs="0"/>
			<xs:element name="rdf" type="statistics_t" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="config_t">
		<xs:sequence>
			<xs:element name="delta" type="xs:double"/>
			<xs:element name="end" type="xs:double"/>
			<xs:element name="output" type="output_t"/>
			<xs:element name="simulationFile" type="xs:string"/>
			<xs:element name="saveFile" type="xs:string" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:element name="configSim" type="config_t"/>
</xs:schema>

=== molekulardynamik/projekt/profileConfig.xml
<?xml version="1.0"?>
<configSim xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="config.xsd">

  <delta>0.0005</delta>
  <end>0.1</end>
  <output>
    <dir>vtkOutput/</dir>
    <filename>profiling_vtk_</filename>
    <iterations>1000</iterations>
    <!--<profile filename="test_profile" iterations="1000"/>-->
  </output>
  <simulationFile>testRayleighTaylor3D.xml</simulationFile>
  <!--<saveFile>Drop.xml</saveFile>-->
</configSim>

<!--single 611s-->
<!--quad 354s-->

=== molekulardynamik/projekt/Blatt5/task5.xml
<?xml version="1.0"?>
<configSim xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../config.xsd">
       
	<delta>0.001</delta>
  	<end>150</end>
  	<output>
  		<dir>Blatt5/vtkOutput/</dir>
  		<filename>equilibrated_fluid_vtk_</filename>
  		<iterations>50</iterations>
  	</output>
  	<simulationFile>Crystallization1.xml</simulationFile>
	<saveFile>Blatt5/equilibrated_fluid.xml</saveFile>
</configSim>

=== molekulardynamik/projekt/Blatt5/task4.xml
<?xml version="1.0"?>
<configSim xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../config.xsd">
       
	<delta>0.0005</delta>
  	<end>500</end>
  	<output>
  		<dir>Blatt5/vtkOutput/</dir>
  		<filename>nanoFlow_vtk_</filename>
  		<iterations>100</iterations>
		<velocityProfile filename="Blatt5/VelocityProfile/nanoFlow_" iterations="10000"/>
  	</output>
  	<simulationFile>nanoFlow.xml</simulationFile>
</configSim>

=== molekulardynamik/projekt/Blatt5/task1.xml
<?xml version="1.0"?>
<configSim xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../config.xsd">
       
	<delta>0.01</delta>
  	<end>500</end>
  	<output>
  		<dir>Blatt5/vtkOutput/</dir>
  		<filename>membrane_vtk_</filename>
  		<iterations>5</iterations>
  	</output>
  	<simulationFile>membrane.xml</simulationFile>
</configSim>

=== molekulardynamik/projekt/Blatt5/task5.2.xml
<?xml version="1.0"?>
<configSim xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../config.xsd">
       
	<delta>0.001</delta>
  	<end>100</end>
  	<output>
  		<dir>Blatt5/vtkOutput/</dir>
  		<filename>super_cooling_vtk_</filename>
  		<iterations>50</iterations>
		<diffusion filename="Blatt5/Diffusion/diffusionSuperCooling" iterations="1000"/>
		<rdf filename="Blatt5/RDF/rdfSuperCooling_" iterations="10000" />	
  	</output>
  	<simulationFile>Blatt5/superCooling.xml</simulationFile>
</configSim>

=== molekulardynamik/projekt/config.xml
<?xml version="1.0"?>
<configSim xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="config.xsd">
       
	<delta>0.0005</delta>
  	<end>10</end>
  	<output>
  		<dir>vtkOutput/</dir>
  		<filename>RayLeigh3D_Quad_vtk</filename>
  		<iterations>50</iterations>
  	</output>
  	<simulationFile>rayleighTaylor3d.xml</simulationFile>
  	<!--<saveFile>Drop.xml</saveFile>-->

</configSim>

<!--single 611s-->
<!--quad 354s-->

=== molekulardynamik/projekt/Blatt5/task5.1.xml
<?xml version="1.0"?>
<configSim xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../config.xsd">
       
	<delta>0.001</delta>
  	<end>250</end>
  	<output>
  		<dir>Blatt5/vtkOutput/</dir>
  		<filename>cooling_vtk_</filename>
  		<iterations>50</iterations>
		<diffusion filename="Blatt5/Diffusion/diffusionCooling" iterations="1000"/>
		<rdf filename="Blatt5/RDF/rdfCooling_" iterations="10000" />
  	</output>
  	<simulationFile>Blatt5/cooling.xml</simulationFile>
</configSim>

=== molekulardynamik/projekt/Blatt5/task2-3.xml
<?xml version="1.0"?>
<configSim xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../config.xsd">
       
	<delta>0.0005</delta>
  	<end>100</end>
  	<output>
  		<dir>Blatt5/vtkOutput/</dir>
  		<filename>rayleighTaylor3D_vtk_</filename>
  		<iterations>100</iterations>
  	</output>
  	<simulationFile>rayleighTaylor3D.xml</simulationFile>
</configSim>
