=== molekulardynamik/projekt/simulation.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<xs:complexType name="type_t">
		<xs:attribute name="sigma" type="xs:double" default="0"/>
		<xs:attribute name="epsilon" type="xs:double" default="0"/>
		<xs:attribute name="mass" type="xs:double" default="0"/>
	</xs:complexType>
	
	<xs:complexType name="vec3i_t">
		<xs:attribute name="X" type="xs:int" default="0"/>
		<xs:attribute name="Y" type="xs:int" default="0"/>
		<xs:attribute name="Z" type="xs:int" default="0"/>
	</xs:complexType>
	
	<xs:complexType name="vec3d_t">
			<xs:attribute name="X" type="xs:double" default="0"/>
			<xs:attribute name="Y" type="xs:double" default="0"/>
			<xs:attribute name="Z" type="xs:double" default="0"/>
	</xs:complexType>
	
	<xs:complexType name="cuboid_t">
		<xs:sequence>
			<xs:element name="position" type="vec3d_t"/>
			<xs:element name="initialVelocity" type="vec3d_t"/>
			<xs:element name="particleCount" type="vec3i_t"/>
			<xs:element name="spacing" type="xs:double"/>
		</xs:sequence>
		<xs:attribute name="type" type="xs:int" default="0"/>
	</xs:complexType>
	
	<xs:complexType name="sphere_t">
		<xs:sequence>
			<xs:element name="type" type="xs:int"/>
			<xs:element name="position" type="vec3d_t"/>
			<xs:element name="initialVelocity" type="vec3d_t"/>
			<xs:element name="radius" type="xs:int"/>
			<xs:element name="spacing" type="xs:double"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="particle_t">
		<xs:sequence>
			<xs:element name="position" type="vec3d_t"/>
			<xs:element name="velocity" type="vec3d_t"/>
		</xs:sequence>
		<xs:attribute name="type" type="xs:int"/>
	</xs:complexType>
	<xs:complexType name="particleArray_t">
		<xs:sequence>
			<xs:element name="particle" type="particle_t" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>	
	<xs:complexType name="thermostat_t">
		<xs:sequence>
			<xs:element name="numDimensions" type="xs:int"/>
			<xs:element name="initialTemp" type="xs:double"/>
			<xs:element name="targetTemp" type="xs:double"/>
			<xs:element name="step" type="xs:int"/>
			<xs:element name="startTime" type="xs:int"/>
      		<xs:element name="targetTime" type="xs:int"/>
		</xs:sequence>
	</xs:complexType>
  
	<xs:complexType name="simulation_t">
		<xs:sequence>
			<xs:element name="thermostat" type="thermostat_t"/>
			<xs:element name="gravity" type="xs:double"/>
			<xs:element name="domain" type="vec3d_t"/>
      		<xs:element name="boundaries" type="vec3i_t"/>
      		<xs:element name="wallType" type="xs:int"/>
			<xs:element name="rCutOff" type="xs:float"/>
			<xs:element name="type" type="type_t" maxOccurs="unbounded"/>
			<xs:element name="cuboid" type="cuboid_t" minOccurs = "0" maxOccurs="unbounded"/>
			<xs:element name="sphere" type="sphere_t" minOccurs = "0" maxOccurs="unbounded"/>
			<xs:element name="particles" type="particleArray_t" minOccurs = "0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:element name="simulation" type="simulation_t"/>
	
</xs:schema>

=== molekulardynamik/projekt/simulation1.xml
<?xml version="1.0"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="src/simulation.xsd">
       
	<domain X="63" Y="36" Z="1"/>
	<rCutOf>3</rCutOf>
	<type sigma="1" epsilon="1" mass="1"/>
	<type sigma="0.9412" epsilon="1" mass="2"/>
	<cuboid type="0">
		<position X="0.6" Y="2.0" Z="0"/>
		<initialVelocity X="0.0" Y="0.0" Z="0.0"/>
		<particleCount X="50" Y="14" Z="1"/>
		<spacing>1.2</spacing>
	</cuboid>
	<cuboid type="1">
		<position X="0.6" Y="19" Z="0"/>
		<initialVelocity X="0.0" Y="0.0" Z="0.0"/>
		<particleCount X="50" Y="14" Z="1"/>
		<spacing>1.2</spacing>
	</cuboid>
</simulation>

=== molekulardynamik/projekt/rayleighTaylor3D.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="simulation.xsd">

  <thermostat>
    <numDimensions>3</numDimensions>
    <initialTemp>40</initialTemp>
    <targetTemp>40</targetTemp>
    <step>100</step>
    <startTime>0</startTime>
    <targetTime>0</targetTime>
  </thermostat>

  <gravity X="0" Y="-12.44" Z="0"/>

  <domain X="60" Y="24" Z="24"/>

  <boundaries X="3" Y="2" Z="3"/>

  <wallType>2</wallType>

  <rCutOff>4</rCutOff>

  <type mass="15" epsilon="2" sigma="1.15"/>
  <type mass="30" epsilon="2" sigma="1.15"/>
  <type mass="300" epsilon="2" sigma="1.15"/>
  
  <cuboid type="0">
  	<position X="0.6" Y="1" Z="0.6"/>
	<initialVelocity X="0.0" Y="0.0" Z="0.0"/>
	<particleCount X="49" Y="5" Z="19"/>
	<spacing>1.2</spacing>
  </cuboid>
  <cuboid type="1">
  	<position X="0.6" Y="8.2" Z="0.6"/>
	<initialVelocity X="0.0" Y="0.0" Z="0.0"/>
	<particleCount X="49" Y="5" Z="19"/>
	<spacing>1.2</spacing>
  </cuboid>

</simulation>

=== molekulardynamik/projekt/Liquid.xml
<?xml version="1.0"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="simulation.xsd">
	<thermostat>
		<numDimensions>2</numDimensions>
  		<initialTemp>0.5</initialTemp>
  		<targetTemp>0.5</targetTemp>
  		<step>1000</step>
  		<startTime>0</startTime>
      <targetTime>0</targetTime>
  	</thermostat>
  	<gravity>-12.44</gravity>
	<domain X="303" Y="180" Z="1"/>
  	<boundaries Left="3" Right="3" Bottom="2" Top="2"/>  	
  	<wallType>1</wallType>
	<rCutOff>3</rCutOff>
	<type sigma="1.2" epsilon="1" mass="1"/>
	<type sigma="1.2" epsilon="1" mass="100"/>
	<cuboid type="0">
		<position X="1.5" Y="2" Z="0"/>
		<initialVelocity X="0.0" Y="0.0" Z="0.0"/>
		<particleCount X="250" Y="50" Z="1"/>
		<spacing>1.2</spacing>
	</cuboid>
</simulation>

=== molekulardynamik/projekt/simulation2.xml
<?xml version="1.0"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="simulation.xsd">
       
    <thermostat>
  		<initialTemp>40</initialTemp>
  		<targetTemp>40</targetTemp>
  		<step>1000</step>
  		<startTime>-1</startTime>
      <targetTime>0</targetTime>
  	</thermostat>
  	<gravity>-12.5</gravity>
	<domain X="150" Y="27" Z="1"/>
  <boundaries Left="2" Right="3" Bottom="1" Top="1"/>
	<rCutOff>3</rCutOff>
	<type sigma="1.2" epsilon="1" mass="1"/>
	<type sigma="1.1" epsilon="1" mass="2"/>
	<cuboid type="0">
		<position X="0.6" Y="2.0" Z="0"/>
		<initialVelocity X="0.0" Y="0.0" Z="0.0"/>
		<particleCount X="125" Y="10" Z="1"/>
		<spacing>1.2</spacing>
	</cuboid>
	<cuboid type="1">
		<position X="0.6" Y="14" Z="0"/>
		<initialVelocity X="0.0" Y="0.0" Z="0.0"/>
		<particleCount X="125" Y="10" Z="1"/>
		<spacing>1.2</spacing>
	</cuboid>
</simulation>

=== molekulardynamik/projekt/Crystallization1.xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="simulation.xsd">

  <thermostat>
    <numDimensions>3</numDimensions>
    <initialTemp>0.01</initialTemp>
    <targetTemp>3.0</targetTemp>
    <step>1</step>
    <startTime>40</startTime>
    <targetTime>80</targetTime>
  </thermostat>

  <gravity X="0" Y="0" Z="0"/>

  <domain X="9.2" Y="9.2" Z="9.2"/>

  <boundaries X="3" Y="3" Z="3"/>

  <wallType>2</wallType>

  <rCutOff>2.3</rCutOff>
  <smoothedLJRadius>1.9</smoothedLJRadius>

  <type mass="1" epsilon="1" sigma="1"/>
  <type mass="300" epsilon="1" sigma="1"/>

  <cuboid type="0">
    <position X="0.575" Y="0.575" Z="0.575"/>
    <initialVelocity X="0.0" Y="0.0" Z="0.0"/>
    <particleCount X="8" Y="8" Z="8"/>
    <spacing>1.15</spacing>
  </cuboid>

</simulation>

=== molekulardynamik/projekt/collisionOfTwoBodies.xml
<?xml version="1.0"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="simulation.xsd">
	<thermostat>
		<numDimensions>2</numDimensions>
  		<initialTemp>20</initialTemp>
  		<targetTemp>20</targetTemp>
  		<step>500</step>
  		<startTime>0</startTime>
      <targetTime>0</targetTime>
  	</thermostat>
  	<gravity>-12.5</gravity>
	<domain X="111" Y="63" Z="1"/>
  	<boundaries Left="3" Right="3" Bottom="2" Top="2"/>  	
  	<wallType>1</wallType>
	<rCutOff>3</rCutOff>
	<type sigma="1" epsilon="5" mass="1"/>
	<type sigma="1" epsilon="5" mass="100"/>
	<cuboid type="0">
		<position X="10.0" Y="5.0" Z="0"/>
		<initialVelocity X="0.0" Y="0.0" Z="0.0"/>
		<particleCount X="80" Y="20" Z="1"/>
		<spacing>1.125</spacing>
	</cuboid>
	<cuboid type="0">
		<position X="60" Y="35" Z="0"/>
		<initialVelocity X="0.0" Y="0.0" Z="0.0"/>
		<particleCount X="20" Y="20" Z="1"/>
		<spacing>1.125</spacing>
	</cuboid>
	<particles>
		<particle type="1">
			<position X="30.5" Y="50" Z="0"/>
			<velocity X="0.0" Y="-1.0" Z="0.0"/>
		</particle>
	</particles>
</simulation>
